# Generated by Django 2.2.4 on 2019-08-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190814_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='objects', to='blog.Category'),
        ),
    ]
